import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Home1 from '../Home'
export default function Home() {
  return (
    <div className='mx-0'>
      <Head>
        <title>Charity Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Home1/>
    </div>
  )
}
